---
- name: playbook for restting of ebs snapshot
  hosts: localhost
  tasks:
  - name: reset snapshots
    command: aws ec2 reset-snapshot-attribute --snapshot-id snap-06bc3a22c0babd747 --attribute createVolumePermission
