---
- name: playbook for attach volume
  hosts: localhost
  become: true
  tasks:
  - name: attach volume
    ec2_vol:
      region: ap-south-1
      volume_type: gp2
      iops: 100
      #snapshot: snap-0443d84c4d094af1a
      instance: i-0d5a850f1681eba5c
      volume_size: 4
      device_name: /dev/sdb    

# Attach an existing volume to instance. The volume will be deleted upon instance termination. 
#  - ec2_vol:
#    instance: XXXXXX
#    id: XXXXXX
#    device_name: /dev/sdf
#    delete_on_termination: yes
